server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # WebSocket 日志流，前端发送【ws会准确匹配到这里
    location /api/ws/ {
        proxy_pass http://aiops-backend:8000/api/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # 普通 API
    location /api/ {
        proxy_pass http://aiops-backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 120s;
    }

    # 前端 SPA
    location / {
        try_files $uri $uri/ /index.html;
    }
}